import shell from 'shelljs'
// const shell = require('shelljs')

shell.rm('-Rf', 'prod')
shell.mkdir('prod')
shell.mkdir('prod/devops')
shell.mkdir('prod/src')
shell.mkdir('prod/src/lib')
shell.cp('-R', 'package.json', 'prod/package.json')
shell.cp('-R', '.svelte-kit', 'prod/.svelte-kit')
shell.cp('-R', 'static', 'prod/static')
shell.cp('-R', 'svelte.config.js', 'prod/svelte.config.js')
shell.cp('-R', 'vite.config.ts', 'prod/vite.config.ts')
shell.cp('-R', 'src/lib/config', 'prod/src/lib/config')
shell.cp('-R', 'devops/ecosystem.config.cjs', 'prod/ecosystem.config.cjs')
shell.cp('-R', 'devops/index.cjs', 'prod/devops/index.cjs')
