@HOSTNAME = http://localhost:5173

###
POST {{HOSTNAME}}/api/auth/verify-otp
Content-Type: application/json

{
    "phone":"8895092508",
    "otp": "1111"
}

###
GET {{HOSTNAME}}/api/admin/categories

###
POST {{HOSTNAME}}/api/admin/categories
Content-Type: application/json

{
    "id": "yokjw7riz0g4qn63vcyorxum",
    "title": "Product1",
    "description": "Product description",
    "slug": "product4",
    "type": "note"
}

###
GET {{HOSTNAME}}/api/admin/categories

###
POST {{HOSTNAME}}/api/admin/categories
Content-Type: application/json

{
    "id": "yokjw7riz0g4qn63vcyorxum",
    "isActive": true
}

###
GET {{HOSTNAME}}/api/admin/categories/{id}

###
POST {{HOSTNAME}}/api/admin/categories
Content-Type: application/json

{
    "id": "MmYLj5banvnH-1NlptZGF",
    "title": "Product5",
    "description": "Product description5",
    "slug": "product5",
    "type": "note"
}

###
DELETE {{HOSTNAME}}/api/admin/categories/{id}
